spring.application.name=microservicio

spring.datasource.driver-class-name=org.postgresql.Driver

# Si realizamos un cambio en nuestros entitys, esta linea se asegurara de mantener el entity "sincronizado" con la base de datos
spring.jpa.hibernate.ddl-auto=update

# Mostrar sql por consola
spring.jpa.show-sql=true

# Legibilidad de codigo sql
spring.jpa.properties.hibernate.format_sql=true